config/routes.rb
Rails.application.routes.draw do
  
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :products
    resources :cities
    resources :users
    resources :orders do
      patch :delivered, on: :member
    end
    resources :states
    resources :administrators, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    namespace :profile do
      resources :dashboard, only: [:index] 
      resources :addresses
      resources :users
      resources :orders do
        patch :delivered, on: :member
      end
    end
    resources :home, only: [:show, :index] 
  end

  devise_for :administrators, :skip => [:registrationsS]
  devise_for :users
  
  root 'site/home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :address
  has_many :orders
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController
    before_action :set_user, only: [:edit, :update, :destroy]
    
    def index
        @users = User.all
    end

    def edit
    end
  
    def update
      passwd = params[:user][:password]
      passwd_confirmation = params[:user][:password_confirmation]
  
      if passwd.blank? && passwd_confirmation.blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
  
      if @user.update(params_user)
        redirect_to backoffice_users_path, notice: "Usuário atualizado!"
      else
        render :edit
      end
    end
  
    def destroy
      if @user.destroy
        redirect_to backoffice_users_path, notice: "Usuário deletado!"
      else
        render :index
      end
    end
  
  
    private
  
      def set_user
        @user = User.find(params[:id])
      end
  
      def params_user
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/controllers/site/profile/addresses_controller.rb
class Site::Profile::AddressesController < Site::ProfileController
    before_action :set_addresses, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.address
  end

  def edit
  
  end

  def update
    if @addresses.update(params_addresses)
      redirect_to site_profile_addresses_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @addresses = Address.new
  end

  def create
    @addresses = Address.new(params_addresses)

    if @addresses.save
      redirect_to site_profile_addresses_path, notice: "Endereço cadastrado com sucesso!"
    else
      render :new
    end
  end

  def destroy
    if @addresses.destroy
      redirect_to site_profile_addresses_path, notice: "Endereço deletado!"
    else
      render :index
    end
  end

  private

    def set_addresses
      @addresses = Address.find(params[:id])
    end

    def params_addresses
      params.require(:address).permit(:id, :user_id, :city_id, :street, :neighborhood, :number)
    end
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController
    
    def index
        
    end
end

app/controllers/site/profile/orders_controller.rb
class Site::Profile::OrdersController < Site::ProfileController
    def index
       @orders = current_user.orders
    end

    def create
        @product = Product.find(orders_params[:product_id])

        @order = current_user.orders.new(address_id: orders_params[:address_id])

        @order.build_products_order(unitary_value: @product.price,
                                    quantity: orders_params[:quantity],
                                    product_id: @product.id)

        if @order.save
            redirect_to site_profile_orders_path, notice: 'Sucesso'
        else
            redirect_to site_home_path(@product), notice: 'Deu ruim'
        end

    end

    def delivered
        @order = Order.find(params[:id])
        if @order.update(delivered: true)
            redirect_to site_profile_orders_path, notice: ''
        else
            redirect_to site_profile_orders_path, notice: ''
        end
    end

    private

    def orders_params
        params.require(:order).permit(:quantity, :address_id, :product_id)
    end
end

app/controllers/site/profile/users_controller.rb
class Site::Profile::UsersController < Site::ProfileController

    def index
        @user = User.find(current_user)
    end
    
    def edit
        @user = User.find(current_user)
    end
    
    def update
        @user = User.find(current_user)
        passwd = params[:user][:password]
        passwd_confirmation = params[:user][:password_confirmation]
    
        if passwd.blank? && passwd_confirmation.blank?
            params[:user].delete(:password)
            params[:user].delete(:password_confirmation)
        end
    
        if @user.update(params_user)
            if passwd.blank? && passwd_confirmation.blank?
                redirect_to site_profile_users_path
            else    
                redirect_to new_user_session_path
            end
        else
            render :edit
        end
    end
    
    
    private
        def params_user
            params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
        end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
    before_action :authenticate_user!
    layout "profile"
    
    def index
    
    end
end
  

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/site/profile/addresses_helper.rb
module Site::Profile::AddressesHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/helpers/site/profile/orders_helper.rb
module Site::Profile::OrdersHelper
end

app/helpers/site/profile/users_helper.rb
module Site::Profile::UsersHelper
end

app/views/site/profile/users/edit.html.erb
<h2><strong>Dados Pessoais</strong></h2>
    <%= form_for([:site, :profile, @user], html: { multipart: true }) do |f| %>
    <div class="row">
        <div class="col-6">
        <div class="form-group">
            <label>Nome:</label>
            <%= f.text_field :name, value: "#{current_user.name}", class: "form-control", required: true %>
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
        <div class="form-group">
            <label>Telefone:</label>
            <%= f.text_field :phone, value: "#{current_user.phone}", class: "form-control", required: true, maxlength:"9" %>
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
        <div class="form-group">
            <label>Email:</label>
            <%= f.text_field :email, class: "form-control", required: true %>
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Senha:</label>
                <%= f.password_field :password, class: "form-control" %>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Confirmação de Senha:</label>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
        </div>
    </div>
    <%= submit_tag "Salvar", class: "btn btn-success"  %>
<% end %>

app/views/site/profile/users/index.html.erb
<h2><strong>Dados Pessoais</strong></h2>
<%= form_for([:site, :profile, @user], html: { multipart: true }) do |f| %>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <label>Nome:</label>
        <%= f.text_field :name, value: "#{current_user.name}", class: "form-control", readonly: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <label>Telefone:</label>
        <%= f.text_field :phone, value: "#{current_user.phone}", class: "form-control", readonly: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div class="form-group">
        <label>Email:</label>
        <%= f.text_field :email, value: "#{current_user.email}", class: "form-control", readonly: true %>
      </div>
    </div>
  </div>
   <%= link_to edit_site_profile_user_path(current_user), class: "pull-left btn btn-success btn-circle" do %>
        EDITAR DADOS
    <% end %>
<% end %>