config/routes.rb
Rails.application.routes.draw do
  
  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :products
    resources :cities
    resources :users
    resources :orders do
      patch :delivered, on: :member
    end
    resources :states
    resources :administrators, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    namespace :profile do
      resources :dashboard, only: [:index] 
      resources :addresses
      resources :users
      resources :orders do
        patch :delivered, on: :member
      end
    end
    resources :home, only: [:show, :index] 
  end

  devise_for :administrators, :skip => [:registrationsS]
  devise_for :users
  
  root 'site/home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
    validates_presence_of :description, :quantity, :price

    has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/backoffice/administrators_controller.rb
class Backoffice::AdministratorsController < BackofficeController
  before_action :set_administrator, only: [:edit, :update, :destroy]

  def index
    @administrators = Administrator.all
  end

  def new
    @administrator = Administrator.new
  end

  def create
    @administrator = Administrator.new(params_administrator)
    if @administrator.save
      redirect_to backoffice_administrators_path, notice: "Administrador cadastrado!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    passwd = params[:administrator][:password]
    passwd_confirmation = params[:administrator][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:administrator].delete(:password)
      params[:administrator].delete(:password_confirmation)
    end

    if @administrator.update(params_administrator)
      redirect_to backoffice_administrators_path, notice: "Administrador atualizado!"
    else
      render :edit
    end
  end

  def destroy
    if @administrator.destroy
      redirect_to backoffice_administrators_path, notice: "Administrador deletado!"
    else
      render :index
    end
  end


  private

    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    def params_administrator
      params.require(:administrator).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/backoffice/cities_controller.rb
class Backoffice::CitiesController < BackofficeController
  before_action :set_city, only: [:edit, :update, :destroy]

  def index
    @cities = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to backoffice_cities_path, notice: "Cidade cadastrada!"
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @city.update(city_params)
      redirect_to backoffice_cities_path, notice: "Cidade atualizada!"
    else
      render :edit
    end
  end

  def destroy
    if @city.destroy
      redirect_to backoffice_cities_path, notice: "Cidade deletada!"
    else
      render :index
    end
  end

  private

    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:description, :state_id, :cep)
    end  
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/orders_controller.rb
class Backoffice::OrdersController < BackofficeController
    def index
        @orders = Order.all
    end

    def delivered
        @order = Order.find(params[:id])
        if @order.update(delivered: true)
            redirect_to backoffice_orders_path, notice: 'Produto entregue'
        else
            redirect_to backoffice_orders_path, notice: 'Falha ao entregar'
        end
    end
end

app/controllers/backoffice/products_controller.rb
class Backoffice::ProductsController < BackofficeController

  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to backoffice_products_path, notice: "Produto cadastrado!"
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @product.update(product_params)
      redirect_to backoffice_products_path, notice: "Produto atualizado!"
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to backoffice_products_path, notice: "Produto deletado!"
    else
      render :index
    end
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :quantity, :price, :image)
    end  

end

app/controllers/backoffice/states_controller.rb
class Backoffice::StatesController < BackofficeController

  before_action :set_state, only: [:edit, :update, :destroy]

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to backoffice_states_path, notice: "Estado cadastrado!"
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @state.update(state_params)
      redirect_to backoffice_states_path, notice: "Cidade atualizado!"
    else
      render :edit
    end
  end

  def destroy
    if @state.destroy
      redirect_to backoffice_states_path, notice: "Cidade deletado!"
    else
      render :index
    end
  end

  private

    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:description)
    end  
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < BackofficeController
    before_action :set_user, only: [:edit, :update, :destroy]
    
    def index
        @users = User.all
    end

    def edit
    end
  
    def update
      passwd = params[:user][:password]
      passwd_confirmation = params[:user][:password_confirmation]
  
      if passwd.blank? && passwd_confirmation.blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
  
      if @user.update(params_user)
        redirect_to backoffice_users_path, notice: "Usuário atualizado!"
      else
        render :edit
      end
    end
  
    def destroy
      if @user.destroy
        redirect_to backoffice_users_path, notice: "Usuário deletado!"
      else
        render :index
      end
    end
  
  
    private
  
      def set_user
        @user = User.find(params[:id])
      end
  
      def params_user
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_administrator!
    layout "backoffice"
end

app/helpers/backoffice/administrators_helper.rb
module Backoffice::AdministratorsHelper
end

app/helpers/backoffice/cities_helper.rb
module Backoffice::CitiesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/orders_helper.rb
module Backoffice::OrdersHelper
end

app/helpers/backoffice/products_helper.rb
module Backoffice::ProductsHelper
end

app/helpers/backoffice/states_helper.rb
module Backoffice::StatesHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/views/backoffice/products/edit.html.erb
<%= render partial: "backoffice/products/shared/form", 
           locals: {name: "Editar produto"} %> 

app/views/backoffice/products/index.html.erb
<h1 class="page-header"><strong>Produtos</strong></h1>
<% if notice %>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= notice %>
    </div>
<% end %>
<div class="panel panel-default">
    <div class="panel-heading">
        Lista de Produtos
        <%= link_to new_backoffice_product_path  do %>
            <button type="button" class="btn btn-success btn-circle pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>
            </button>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Quantidade</th>
                        <th>Preço</th>
                        <th style="width: 9.5%">Opções</th>
                    </tr>
                </thead>
                <tbody>
                    <% @products.each do |product| %>
                        <tr>
                            <td><%= product.id %></td>
                            <td><%= product.name %></td>
                            <td><%= product.quantity %></td>
                            <td><%= product.price %></td>
                            <td>
                                <%= link_to edit_backoffice_product_path(product), class: "btn btn-warning btn-circle" do %>
                                    <i class="fa fa-pencil"></i>
                                <% end %>
                                <%= link_to backoffice_product_path(product),  method: :delete, class: "btn btn-danger btn-circle",
                                                                               data: { confirm: 'Você deseja realmente excluir?' } do %>
                                    <i class="fa fa-trash"></i>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/backoffice/products/new.html.erb
<%= render partial: "backoffice/products/shared/form", 
           locals: {name: "Novo produto"} %>    